#!/bin/bash

# Check for input argument
if [ $# -eq 0 ]
  then
    echo "Usage: twc <command> <option>"
    exit 1
fi

command=$1
if command -v twc-${command}.sh >/dev/null 2>&1
  then
    script=twc-${command}.sh
elif command -v twc-${command}-webcast.sh >/dev/null 2>&1
  then
    script=twc-${command}-webcast.sh
elif [[ ${command} == tmpdir ]]
  then
    script=twc-create-tmpdir.sh
fi

if [ $# > 1 ]
  then
    ${script} $2
else
	${script}
fi

rm 1
